monitor=,preferred,auto,1

$mainMod = SUPER
exec-once = sleep 2 && copyq
exec-once = sleep 1 && waybar
exec-once = mako
exec-once = copyq
exec-once = nm-applet
exec-once = blueman-applet
exec-once = swaybg -i ~/Pictures/wallpapers/wall.jpg -m fill
exec-once = hypridle
env = XCURSOR_SIZE,24

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 6
    gaps_out = 10
    border_size = 2

    col.active_border = rgba(89b4faff)
    col.inactive_border = rgba(313244aa)

    layout = dwindle
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 5
        passes = 2
    }
}

animations {
    enabled = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
bind = $mainMod, X, exec, wlogout
bind = $mainMod, Escape, exec, hyprlock
bind = $mainMod, Escape, exec, swaylock --screenshots --clock --indicator --grace 2 --fade-in 0.2
bind = , Print, exec, grim ~/Pictures/$(date +%s).png
bind = SHIFT, Print, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod, B, exec, brave
bind = $mainMod, E, exec, nautilus
bind = SUPER, SPACE, exec, rofi -show drun
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod SHIFT, F, togglefloating

bind = $mainMod, V, exec, copyq toggle

bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t

bind = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

